//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suhoro.WindowsTool.ShortcutKey.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class SettingsPlugin : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPlugin defaultInstance = ((SettingsPlugin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPlugin())));
        
        public static SettingsPlugin Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int HotKeyInterval {
            get {
                return ((int)(this["HotKeyInterval"]));
            }
            set {
                this["HotKeyInterval"] = value;
            }
        }
    }
}
