//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suhoro.WindowsTool.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class SettingsApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsApp defaultInstance = ((SettingsApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsApp())));
        
        public static SettingsApp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoStart {
            get {
                return ((bool)(this["IsAutoStart"]));
            }
            set {
                this["IsAutoStart"] = value;
            }
        }
    }
}
