//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suhoro.WindowsTool.FloatingIcon.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class SettingsPlugin : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsPlugin defaultInstance = ((SettingsPlugin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsPlugin())));
        
        public static SettingsPlugin Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int IconWidth {
            get {
                return ((int)(this["IconWidth"]));
            }
            set {
                this["IconWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int IconHeight {
            get {
                return ((int)(this["IconHeight"]));
            }
            set {
                this["IconHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color HiddenColor {
            get {
                return ((global::System.Drawing.Color)(this["HiddenColor"]));
            }
            set {
                this["HiddenColor"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("defaultFloatingIcon.png")]
        public string DefaultFloatingIconName {
            get {
                return ((string)(this["DefaultFloatingIconName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomFloatingIconName {
            get {
                return ((string)(this["CustomFloatingIconName"]));
            }
            set {
                this["CustomFloatingIconName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://siteoforigin:,,,/Resources")]
        public string UriResources {
            get {
                return ((string)(this["UriResources"]));
            }
        }
    }
}
